### ISSUE TITLE
다국어 지원

### ISSUE THREAD

**Issue by yeahg-dev** [yeahg-dev/Chajabwa#18]
## 🎯 목적
- 한국어, 영어, 2가지 언어를 지원해서 한국 외 국가에서의 접근성 확보
 
<br>

### 지역화 적용 대상
- String : .strings 파일을 기반으로 `localizedString`사용
- AssetCatalog : `loacalization` 기능 사용
- Date : `DateFormatter`사용하여 region에 알맞은 날짜 포맷 표시

<br>

## ✅ Task
- 언어/지역 설정 기능
  - [x] 선호 언어 설정 기능 (localization)
  - [x] 검색 국가 설정 기능 (SearchAPI에 적용)
- 현재 기기 설정을 제공하는 API 구현
  - [x] DeviceSetting 타입 구현
- Asset
  - [ ] 런치스크린
- Date Format
  - [ ] DateFormatter

<br>
